apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: build-suite-test-component-git-source-hlza
  namespace: build-templates-e2e
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: build-suite-test-application-abqm
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: build-suite-test-component-git-source-hlza
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: build-suite-test-component-git-source-hlza-
      labels:
        build.appstudio.openshift.io/application: build-suite-test-application-abqm
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: build-suite-test-component-git-source-hlza
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: build-templates-e2e
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-hello-world
      - name: output-image
        value: quay.io/redhat-appstudio/test-images:f9978f00c2fc4cb6b15e313d2d204d13-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/pull-request-builds:base-55c198892c6e297bfb2a92bd359b853013f69a0d
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: build-suite-test-component-git-source-hlza/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
